FROM ghcr.io/astral-sh/uv:python3.11-slim

ENV UV_PROJECT_ENV=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

COPY pyproject.toml ./
COPY README.md ./
COPY src ./src

RUN uv pip install --system --no-cache .

COPY . .

CMD ["python", "main.py"]

